Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-07, with the labels that each got.

#737 Clarify that the cli is ran locally in an app and not installed globally
  docs/quick-start.md
Labels: documentation

#739 Adds Discord third-party Supabase auth provider
  docs/authentication.md
Labels: documentation, next-release/wait-to-merge

#743 Document GraphQL Handler configuration, logger options, and security measures
  docs/graphql.md
  docs/logger.md
  docs/security.md
Labels: documentation

#736 Logger documentation clarifies log level and adds Papertrail example
  docs/logger.md
Labels: documentation

#722 Adds docs for dbAuth
  docs/authentication.md
Labels: next-release/wait-to-merge

#711 [v0.34] Documents netlify.toml and dev config when using setup deploy netlify
  docs/cliCommands.md
Labels: documentation

#757 Fix type-check typo and add it to CLI command doc
  docs/cliCommands.md
  docs/typescript.md
Labels: documentation

#748 Documents how to customize and enrich the context in the GraphQL Handler
  docs/graphql.md
Labels: documentation

#760 Logger: Added a snippet for Honeybadger
  docs/logger.md
Labels: documentation
