Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-10, with the labels that each got.

#793 Adds generator generator docs
  docs/cliCommands.md
Labels: documentation, next-release/wait-to-merge

#788 [v0.37.0] Update for new scenario syntax
  docs/testing.md
Labels: next-release/wait-to-merge

#792 [v0.37] Document using existing data in scenarios
  docs/testing.md
Labels: next-release/wait-to-merge

#801 Draft - [v0.37.0] Document Redwood Directives
  assets/images/require-auth-directive.excalidraw
  assets/images/require-auth-directive.png
  assets/images/welcome-directive.excalidraw
  assets/images/welcome-directive.png
  docs/cliCommands.md
  docs/directives.md
  docs/graphql.md
  docs/services.md
  lib/build.js
Labels: documentation
