Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-11, with the labels that each got.

#867 Update docs for slow query threshold
  docs/logger.md
Labels: hacktoberfest-accepted

#883 Docs: GraphQL Section typo, grammar and markdown tables updates
  docs/graphql.md
Labels: documentation

#888 Document Chakra UI and the new `yarn rw setup ui` command
  docs/cliCommands.md
  docs/webpackConfiguration.md
Labels: next-release/wait-to-merge

#891 Add docs for toml env interpolation
  docs/appConfiguration.md
  yarn.lock
Labels: next-release/wait-to-merge

#887 [v0.39.0] Add docs for isEmpty
  docs/cells.md
Labels: next-release/wait-to-merge

#889 Adds RedwoodRecord docs
  docs/cliCommands.md
  docs/redwoodRecord.md
  lib/build.js
Labels: documentation, next-release/wait-to-merge

#892 Add docs for api url globals
  docs/appConfiguration.md
  docs/environmentVariables.md
Labels: next-release/wait-to-merge

#885 [v0.39.0] Storybook: added documentation for `storybook.manager.js`
  docs/storybook.md
Labels: next-release/wait-to-merge

#882 Router: paramTypes property names
  docs/router.md
Labels: next-release/wait-to-merge

#814 Upgrade Azure Active Directory authentication from msal to @azure/msal-*
  docs/authentication.md
Labels: hacktoberfest-accepted, next-release/wait-to-merge
