Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-08, with the labels that each got.

#774 How to test functions and webhooks
  docs/appConfiguration.md
  docs/serverlessFunctions.md
  docs/testing.md
  docs/webhooks.md
Labels: documentation, next-release/wait-to-merge

#762 Update Supabase auth w/ links and SMS OTP info
  docs/authentication.md
Labels: documentation, next-release/wait-to-merge

#759 Adds Supabase Twitch auth documentation
  docs/authentication.md
Labels: documentation, next-release/wait-to-merge

#750 [v0.36.0] Add documentation for the Clerk auth integration
  docs/authentication.md
Labels: documentation, next-release/wait-to-merge

#718 [v0.36] update Firebase auth docs
  docs/authentication.md
Labels: next-release/wait-to-merge

#754 Explains why db seed is currently Javascript only and links how to use Typescript if so desired
  docs/cliCommands.md
Labels: documentation

#753 [v0.36] Remove doc for db command
  docs/cliCommands.md
Labels: next-release/wait-to-merge

#763 SEO doc update for app title and title template
  docs/appConfiguration.md
  docs/seo.md
  docs/webpackConfiguration.md
Labels: next-release/wait-to-merge

#772 Update Serverless Doc re: serving binary data example https://github.com/redwoodjs/redwood/pull/3219
  docs/serverlessFunctions.md
Labels: next-release/wait-to-merge

#726 Add notes on purging unused Tailwind CSS
  docs/webpackConfiguration.md
Labels: documentation
