Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-02, with the labels that each got.

#531 [v0.24] Updates Supabase Authentication documentation with OAuth and magiclink support
  code/html/index.html
  code/html/logos.html
  code/html/roadmap.html
  code/html/stickers-thanks.html
  code/html/stickers.html
  docs/authentication.md
Labels: documentation

#552 Modify self-hosting build command for prisma deploy
  cookbook/Self-hosting_Redwood.md
Labels: documentation

#555 Improve local postgres setup
  docs/localPostgresSetup.md
Labels: documentation

#550 Add prisma section, deprecate db section
  docs/cliCommands.md
Labels: documentation

#554 Update misc. yarn rw db references
  cookbook/File_Upload.md
  docs/quick-start.md
Labels: documentation

#543 [v0.25] Adds Facebook as supported Supabase provider
  docs/authentication.md
Labels: documentation

#565 Add missing line breaks
  docs/cliCommands.md
Labels: documentation

#566 Edit serverless function doc for coherence
  docs/serverlessFunctions.md
Labels: documentation

#568 Tutorial: Switch to double quotes to make command work in Windows Cmd
  TUTORIAL.md
Labels: tutorial, windows

#571 Improve recruiting language in WIP disclaimer
  docs/serverlessFunctions.md
Labels: documentation

#572 Add "WIP" copy to the docs that need it
  docs/assetsAndFiles.md
  docs/builds.md
  docs/connectionPooling.md
  docs/typescript.md
Labels: documentation

#573 Edit mock graphql mock request doc
  docs/mockGraphQLRequests.md
Labels: documentation

#564 Edit custom function cookbook
  cookbook/Custom_Function.md
Labels: documentation

#588 Correct dataMigrate commands to use prisma migrate
  docs/cliCommands.md
  docs/dataMigrations.md
Labels: documentation

#589 Add "Custom Index" doc
  docs/cliCommands.md
  docs/customIndex.md
  lib/build.js
Labels: documentation, enhancement

#590 Add prerender doc
  docs/prerender.md
  lib/build.js
Labels: documentation, enhancement

#562 [v0.26.0] Add Nhost to Auth Docs
  code/html/index.html
  code/html/logos.html
  code/html/roadmap.html
  code/html/stickers-thanks.html
  code/html/stickers.html
  docs/authentication.md
Labels: documentation, enhancement

#596 Rename setup index to setup web index
  docs/cliCommands.md
  docs/customIndex.md
Labels: bug
