Repository redwoodjs/redwoodjs.com, pull requests merged in 2021-01, with the labels that each got.

#407 Support Azure AD authentication: Documentation
  docs/authentication.md
Labels: documentation, hacktoberfest-accepted

#503 Document the rw console command
  docs/cliCommands.md
Labels: documentation

#504 Updates Supabase auth setup instructions for 1.0
  docs/authentication.md
Labels: documentation

#421 Tutorial Part II
  .gitignore
  TUTORIAL.md
  TUTORIAL2.md
  code/html/_nav.html
  code/html/tutorial2/.keep
  code/stylesheets/markdown.pcss
  lib/build.js
  lib/docutron.js
  netlify.toml
  package.json
  yarn.lock
Labels: hacktoberfest-accepted

#501 New Auth - Ethereum
  TUTORIAL.md
  docs/authentication.md
Labels: documentation

#527 Add a step in the RBAC section to ensure the success of refetchQuery action after deletion
  TUTORIAL2.md
Labels: cookbook
